name: CI

on:
  push:
    branches:
      - master

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        # The normal requirements.txt is installed as it provides files for mypy to use.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (Pylint)
        run: pylint --rcfile=setup.cfg ./spacexlaunchbot

      - name: Lint (Flake8)
        run: flake8 ./spacexlaunchbot

      - name: Type analysis (MyPy)
        run: mypy ./spacexlaunchbot

      - name: Security analysis (Bandit)
        run: bandit -r ./spacexlaunchbot

      - name: Unused code detection (Vulture)
        run: vulture --ignore-names on_* ./spacexlaunchbot

      - name: Tests
        run: pytest
        env:
          SLB_API_TOKEN_DISCORD: for-testing
          SLB_API_TOKEN_BOT_LIST_DBL: for-testing
          SLB_API_TOKEN_BOT_LIST_BOD: for-testing
          SLB_API_TOKEN_BOT_LIST_DBG: for-testing
          SLB_API_TOKEN_BOT_LIST_BFD: for-testing

      - name: Build Docker image
        run: docker build -t psidex/spacexlaunchbot .

      - name: Push Docker image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push psidex/spacexlaunchbot
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
